/*
* Autogenerated by Route Type Compiler (1.2.6)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
/* tslint:disable */

import Hello from '../server/route/hello';

declare module '@mtfe/http-rpc-client' {
  const hello: Hello;
  export interface IGetRoute {
    '/api/hello, HttpMethod.GET/api/hello': ReturnType<typeof hello.hello >
  }
  export interface IPostRoute {
    
  }
}
